name: Shop Floor Data Collection System

exclude:
  [
    ".sass-cache",
    "node_modules",
    "assets/images/raw",
    "readme.md",
    "package.json",
    "package-lock.json",
    "gulpfile.js",
  ]

include: ["_redirects"]

plugins:
  - jekyll-menus
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "post"
